---
# Source directory is here
SRC_DIR: "/opt/scsim"
#Prototype .fa files are stored here
REF_DIR: "data/scref/"
#Some temporary files and mutation references (.txt and .vcf) files are stored here
SAMPLE_DIR: "data/screads/"
#The final bulk .bam files are stored here
BULK_DIR: "data/bulk_reads/"
#The final single cell .bam files are stored here
SC_DIR: "data/sc_reads/"
#Log files are stored here
LOGS_DIR: "logs/"
#The results of variant callers are stored here
CALLS_DIR: "calls/"


#Reference genome you want to use to generate the simulated single cells
REFGENOME: "data/chr20/chr20.fa"
#Number of single cells to generate
NSC: 2
#Number of read-error free prototypes to generate
NPROTO: 2
#Number of single nucleotide variants each cell will have
NSNV: 100
#Number of bulk samples to generate
NBulk: 2
#Random seed for reproducibility
SEED: 10696
#Mean coverage depth to generate for each cell
MEAN_COV: 24
#Per base error rate on read #1
PBE1: 0.002
#Per base error rate on read #2 (reverse read)
PBE2: 0.002
#Allelic dropout rate
ADO_p: 0.2
#False positive rate
FP_p: 3.2e-5


IND_1:
    BIO_1:
        SAMP_1: {BULK: True}
        SAMP_2: {BULK: False}
    BIO_2:
        SAMP_1: {BULK: True}
        SAMP_2: {BULK: False}
IND_2:
    BIO_1:
        SAMP_1: {BULK: True}
        SAMP_2: {BULK: True}
    BIO_2:
        SAMP_1: {BULK: False}
        SAMP_2: {BULK: True}
...
