---
# Source directory is here       ****Include all trailing '/' in directory definitions****
SRC_DIR: "../src/"
# Prototype .fa files are stored here
REF_DIR: "data/mut_ref/"
# The final bulk .bam files are stored here
BULK_DIR: "data/bulk_reads/"
# The final single cell .bam files are stored here
SC_DIR: "data/sc_reads/"
# Log files are stored here
LOGS_DIR: "logs/"
# The results of variant callers are stored here
CALLS_DIR: "calls/"
# The environments to run the tool are stored here
ENVS_DIR: "../envs/"

# Reference genome you want to use to generate the simulated single cells
REFGENOME: "data/chr20/chr20.fa"
# Number of single nucleotide variants each cell will have
NSNV: 100
# Random seed for reproducibility
SEED: 10696
# Mean coverage depth to generate for each single cell
MEAN_COV: 24
# Per base error rate on read #1
PBE1: 0.002
# Per base error rate on read #2 (reverse read)
PBE2: 0.002
# Allelic dropout rate
ADO_p: 0.2
# False positive rate
FP_p: 3.2e-5

POPULATION:
    alpha: [0.1, 0.3, 0.6]
    BIO_1:
        beta: 0.1
        SAMPLE_1:
            gamma: 0.1
            SC: True
        SAMPLE_2:
            gamma: 0.1
            SC: False
    BIO_2:
        beta: 0.1
        SAMPLE_1:
            gamma: 0.1
            SC: True
        SAMPLE_2:
            gamma: 0.1
            SC: True
    BIO_3:
        beta: 0.1
        SAMPLE_1:
            gamma: 0.1
            SC: False
        SAMPLE_2:
            gamma: 0.1
            SC: False
    BIO_4:
        beta: 0.1
        SAMPLE_1:
            gamma: 0.1
            SC: False
        SAMPLE_2:
            gamma: 0.1
            SC: True
...
